#!/usr/bin/env python
# -*- coding: utf-8 -*-

from geometry_msgs.msg import PoseStamped
from geometry_msgs.msg import TransformStamped
import rospy
import tf2_ros

class PublishPoseFromTF:
    def __init__(self):
        self._tf_buffer = tf2_ros.Buffer()
        self._tf_listener = tf2_ros.TransformListener(self._tf_buffer)

        # This frame is used as output pose's reference coordinate
        self._base_frame = rospy.get_param('~base_frame')
        # This frame's pose relative to base_frame will be published as geometry_msgs/PoseStamped
        self._pose_frame = rospy.get_param('~pose_frame')
        # Timeout for lookup transform between base_frame and pose_frame
        self._timeout = rospy.get_param('~timeout', 1.0)

        self._pose_pub = rospy.Publisher('~pose', PoseStamped, queue_size = 1)

        self.main_loop()
    
    def main_loop(self):
        while not rospy.is_shutdown():
            try:
                transform = self._tf_buffer.lookup_transform(self._base_frame, self._pose_frame, rospy.Time.now(), rospy.Duration(self._timeout))
            except:
                continue 

            pose = PoseStamped()
            pose.header.frame_id = self._base_frame
            pose.header.stamp = transform.header.stamp

            pose.pose.position.x = transform.transform.translation.x
            pose.pose.position.y = transform.transform.translation.y
            pose.pose.position.z = transform.transform.translation.z
            pose.pose.orientation = transform.transform.rotation

            self._pose_pub.publish(pose)
            
 
if __name__ == '__main__':
    rospy.init_node('publish_pose_from_tf')
    publish_pose_from_tf = PublishPoseFromTF()
